# Generated by Django 6.0 on 2025-12-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crochetitem',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
